---

name: "Add Issues To Project Board"

"on":
  issues:
    types:
      - opened
env:
  GH_TOKEN: ${{ secrets.GH_NEW_CARD_TO_PROJECT }}
  PROJECT_ID: ${{ secrets.FRONT_END_PROJECT_ID }}
  ISSUE_ID: ${{ github.event.issue.node_id }}
  USER: ${{ github.actor }}
  LABEL_ID: [“LA_kwDOFDaR5872-WxC”, “LA_kwDOFDaR588AAAABDzKzWQ”]

jobs:
  add_issue_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: "Add to front end project board"
        run: |
          gh api graphql -f query='
            mutation($user:String!, $project:ID!, $issue:ID!) {
              addProjectV2ItemById(input: {clientMutationId: $user, projectId: $project, contentId: $issue}) {
                item {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f issue=$ISSUE_ID -f user=$USER

      - name: "Add repo identifier label"
        run: |
          gh api graphql -f query='
            mutation($user:String!, $issue:ID!, $label:[ID!]!) {
              addLabelsToLabelable(input: {clientMutationId: $user, labelableId: $issue, labelIds: $label}) {
                clientMutationId
              }
            }' -f label=$LABEL_ID -f issue=$ISSUE_ID -f user=$USER
